const CaseUtils = require('case-utils')

console.log('')
console.log('CaseUtils.camelToKebab() results:')
console.log('')
console.log(`'thisIsATest' becomes: '${CaseUtils.camelToKebab('thisIsATest')}'`)
console.log(`'itemID' becomes: '${CaseUtils.camelToKebab('itemID')}'`)
console.log(`'IsACollider' becomes: '${CaseUtils.camelToKebab('IsACollider')}'`)
console.log(`'PositionX' becomes: '${CaseUtils.camelToKebab('PositionX')}'`)
console.log(`'PlayerID' becomes: '${CaseUtils.camelToKebab('PlayerID')}'`)
console.log(`'IDPlayer' becomes: '${CaseUtils.camelToKebab('IDPlayer')}'`)
console.log(`'ThisIsATest' becomes: '${CaseUtils.camelToKebab('ThisIsATest')}'`)
console.log('')
console.log(`----------------------------`)
console.log('')
console.log('CaseUtils.removeHyphens() results:')
console.log('')
console.log(`'this-is-a-test' becomes: '${CaseUtils.removeHyphens('this-is-a-test')}'`)
console.log('')
console.log(`----------------------------`)
console.log('')
console.log('CaseUtils.toStart() results:')
console.log('')
console.log(`'this is a test' becomes: '${CaseUtils.toStart('this is a test')}'`)

